image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

pages:
  stage: deploy
  script:
    - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
