image: node:latest

services:
  - postgres:10.12-alpine

variables:
  POSTGRES_DB: cloudcoretest
  POSTGRES_USER: cloudcoretest
  POSTGRES_PASSWORD: "cloudcoretest"
  POSTGRES_HOST_AUTH_METHOD: trust
  CI_POSTGRES_HOST: postgres

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y postgresql-contrib
    - psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS 'uuid-ossp';"
  script:
    - npm i
    - npm test

pages:
  stage: deploy
  script:
    - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
