image: node:9-alpine

stages:
  - test

test:
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'
