image: hilderonny/cloudcoretest:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm i
    - npm test

pages:
  stage: deploy
  script:
    - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
