image: node:9-alpine

stages:
  - test

test:
  stage: test
  variables:
    DB_URL: "mongodb://mongo/arrangetest"
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm run-script test
  coverage:
    /All files[^|]*\|[^|]*\s+([\d\.]+)/
