image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - postgres:10.12-alpine
  before_script:
    - psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS 'uuid-ossp';"
  variables:
    POSTGRES_DB: cloudcoretest
    POSTGRES_USER: cloudcoretest
    POSTGRES_PASSWORD: "cloudcoretest"
    POSTGRES_HOST_AUTH_METHOD: trust
    PGHOST: postgres
  script:
    - npm i
    - npm test

pages:
  stage: deploy
  script:
    - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
