image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - lkameris/postgres-uuid
  variables:
    POSTGRES_DB: cloudcoretest
    POSTGRES_USER: cloudcoretest
    POSTGRES_PASSWORD: "cloudcoretest"
    POSTGRES_HOST_AUTH_METHOD: trust
    PGHOST: postgres
  script:
    - npm i
    - npm test

pages:
  stage: deploy
  script:
    - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
